/* ─────────────────────────────────────────────
   js/reportPdf.js — A.I.R.C. Pro
   Generates a real downloadable PDF report using jsPDF
   (loaded from CDN on first use, kept out of the initial
   page weight since not every session needs a PDF).
───────────────────────────────────────────── */
'use strict';

let jsPdfLoaded = false;
async function ensureJsPdf() {
  if (jsPdfLoaded || (window.jspdf && window.jspdf.jsPDF)) { jsPdfLoaded = true; return; }
  await new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
    s.onload = resolve; s.onerror = reject;
    document.head.appendChild(s);
  });
  jsPdfLoaded = true;
}

/**
 * Build and download a PDF interview report.
 * @param {Object} data - { category, difficulty, score, wpm, eyeContact,
 *   fillers, totalWords, duration, questions, answers, breakdowns }
 */
async function exportPdfReport(data) {
  await ensureJsPdf();
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 40;
  let y = 50;

  doc.setFont('helvetica', 'bold'); doc.setFontSize(20);
  doc.text('A.I.R.C. Pro — Interview Report', marginX, y);
  y += 22;
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(90);
  doc.text(`${data.category} · ${data.difficulty} · ${new Date().toLocaleString()}`, marginX, y);
  y += 24;

  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(13);
  doc.text('Performance Summary', marginX, y); y += 16;
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10);
  const grade = data.score >= 80 ? 'A' : data.score >= 65 ? 'B' : data.score >= 50 ? 'C' : 'D';
  const summaryLines = [
    `Overall Score: ${data.score}/100 (Grade ${grade})`,
    `Words per Minute: ${data.wpm}`,
    `Eye Contact: ${data.eyeContact}%`,
    `Filler Words: ${data.fillers}`,
    `Total Words: ${data.totalWords}`,
    `Duration: ${data.duration}`,
  ];
  summaryLines.forEach(line => { doc.text(line, marginX, y); y += 14; });
  y += 10;

  if (data.breakdowns && data.breakdowns.length) {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(13);
    doc.text('Detailed Score Breakdown', marginX, y); y += 16;
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10);
    data.breakdowns.forEach(b => {
      if (y > 760) { doc.addPage(); y = 50; }
      doc.text(`${b.label}: ${b.value}/100`, marginX, y); y += 13;
    });
    y += 10;
  }

  doc.setFont('helvetica', 'bold'); doc.setFontSize(13);
  if (y > 740) { doc.addPage(); y = 50; }
  doc.text('Q&A Review', marginX, y); y += 16;
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10);
  (data.questions || []).forEach((q, i) => {
    if (y > 740) { doc.addPage(); y = 50; }
    doc.setFont('helvetica', 'bold');
    const qLines = doc.splitTextToSize(`Q${i + 1}: ${q}`, 515);
    doc.text(qLines, marginX, y); y += qLines.length * 13 + 2;
    doc.setFont('helvetica', 'normal');
    const ans = data.answers?.[i] || 'No answer recorded';
    const aLines = doc.splitTextToSize(ans, 515);
    if (y + aLines.length * 12 > 780) { doc.addPage(); y = 50; }
    doc.text(aLines, marginX, y); y += aLines.length * 12 + 10;
  });

  doc.setFontSize(8); doc.setTextColor(140);
  doc.text(`Generated by A.I.R.C. Pro · ${new Date().toISOString()}`, marginX, 820);

  doc.save(`airc_report_${Date.now()}.pdf`);
}

window.AIRC_PDF = { exportPdfReport };
